# 数据清洗

## 导入必要的组件

In [1]:
import pandas as pd
from sqlalchemy import create_engine

## 导入csv，UTF-8格式不行所以换成latin-1

In [2]:
df=pd.read_csv("SampleSuperstore.csv",encoding='latin-1')

df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

# 简单检查有无空值

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 1.6+ MB

# 改变日期格式

In [4]:
df['Order Date']=pd.to_datetime(df['Order Date'],format='mixed',dayfirst=False)
df['Ship Date']=pd.to_datetime(df['Ship Date'],format='mixed',dayfirst=False)

df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

# 检查列名有无问题,空格改为下划线，‘-’改成下划线，然后全部改成小写，改成MySql支持的列名

In [6]:
print(df.columns)

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [5]:
df.columns=df.columns.str.replace(' ','_')
df.columns=df.columns.str.replace('-','_')

df.columns=df.columns.str.lower()

print(df.columns)

Index(['row_id', 'order_id', 'order_date', 'ship_date', 'ship_mode',
       'customer_id', 'customer_name', 'segment', 'country', 'city', 'state',
       'postal_code', 'region', 'product_id', 'category', 'sub_category',
       'product_name', 'sales', 'quantity', 'discount', 'profit'],
      dtype='object')

# 生产新字段 利润率

In [6]:
df['profit_margin']=(df['profit']/df['sales']*100).round(2)

df.head()

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country,city,...,region,product_id,category,sub_category,product_name,sales,quantity,discount,profit,profit_margin
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,16.00
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,30.00
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,47.00
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,-40.00
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,11.25

# 用sqlalchemy连接到MySql

In [17]:
engine=create_engine("mysql+pymysql://root:root@127.0.0.1/superstore")

print("连接成功")

连接成功

# 将初步清洗完的数据导入到MySql

In [27]:
df.to_sql('superstore_data',con=engine,schema='superstore',if_exists='replace',index=False)

9994

## 年月表的创建

In [25]:
df_date=df[['order_date']]

df_date.head()

  order_date
0 2016-11-08
1 2016-11-08
2 2016-06-12
3 2015-10-11
4 2015-10-11

In [28]:
df_date = df_date.drop_duplicates(subset=['order_date']).copy()

df_date['yearmonth']=df_date['order_date'].dt.to_period('M')

df_date.head()

   order_date yearmonth
0  2016-11-08   2016-11
2  2016-06-12   2016-06
3  2015-10-11   2015-10
5  2014-06-09   2014-06
12 2017-04-15   2017-04

In [30]:
df_date=df_date.sort_values('order_date')

df_date.head()

     order_date yearmonth
7980 2014-01-03   2014-01
739  2014-01-04   2014-01
1759 2014-01-05   2014-01
5327 2014-01-06   2014-01
7660 2014-01-07   2014-01

In [31]:
df_date.to_sql('date',con=engine,schema='superstore',if_exists='replace',index=False)

1237

In [ ]:
#RFM

In [ ]:
## 设定分析截止日期（以数据中最大日期为基准）

In [9]:
from datetime import datetime,timedelta

max_date=df['order_date'].max()

nalysis_date = max_date + timedelta(days=1)  # 分析截止日期设为最后一天的后一天

print(nalysis_date)

2017-12-31 00:00:00

In [11]:
rfm=df.groupby('customer_id').agg({
    'order_date':lambda x :(nalysis_date-x.max()).days,
    'order_id':'nunique',
    'sales':'sum'
}).round(2)

rfm.columns=['Recency','Frequency','Monetary']

rfm=rfm.reset_index()

rfm.head()

  customer_id  Recency  Frequency  Monetary
0    AA-10315      185          5   5563.56
1    AA-10375       20          9   1056.39
2    AA-10480      260          4   1790.51
3    AA-10645       56          6   5086.93
4    AB-10015      416          3    886.16

In [ ]:
# rfm评分,采用5分位数

In [14]:
# Recency越小分越高
rfm['R_score']=pd.qcut(rfm['Recency'],
                       5,
                       labels=[5,4,3,2,1]).astype(int)

# rank(methon='first')避免排名重复导致qcut报错
rfm['F_score']=pd.qcut(rfm['Frequency'].rank(method='first'),
                       5,
                       labels=[1,2,3,4,5]).astype(int)

rfm['M_score']=pd.qcut(rfm['Monetary'],
                       5,
                       labels=[1,2,3,4,5]).astype(int)

rfm['RFM_score'] = rfm['R_score'] + rfm['F_score'] + rfm['M_score']

rfm.head()

,customer_id,Recency,Frequency,Monetary,R_score,F_score,M_score,RFM_score
0,AA-10315,185,5,5563.56,2,2,5,9
1,AA-10375,20,9,1056.39,5,5,2,12
2,AA-10480,260,4,1790.51,1,1,3,5
3,AA-10645,56,6,5086.93,3,3,5,11
4,AB-10015,416,3,886.16,1,1,1,3

In [ ]:
# 定义客户等级

In [16]:
def customer_seg(row):
    r,f,m=row['R_score'],row['F_score'],row['M_score']

    if r>=4 and f>=4 and m>=4:
        return '高价值客户'
    elif r>=4 and f>=4 and m>=2:
        return '重要发展客户'
    elif r<=2 and f>=4 and m>=4:
        return '重要保持客户'
    elif r>=4 and f==1:
        return '新客户'
    elif r==1:
        return '潜在流失客户'
    else:
        return '一般客户'

rfm['cus_seg']=rfm.apply(customer_seg,axis=1)

rfm.head()

,customer_id,Recency,Frequency,Monetary,R_score,F_score,M_score,RFM_score,cus_seg
0,AA-10315,185,5,5563.56,2,2,5,9,一般客户
1,AA-10375,20,9,1056.39,5,5,2,12,重要发展客户
2,AA-10480,260,4,1790.51,1,1,3,5,潜在流失客户
3,AA-10645,56,6,5086.93,3,3,5,11,一般客户
4,AB-10015,416,3,886.16,1,1,1,3,潜在流失客户

In [18]:
rfm.to_sql('rfm_analysis',con=engine,schema='superstore',if_exists='replace',index=False)

793